### ISSUE TITLE
Just use "sans-serif" as fallback

### ISSUE THREAD

**Issue by callumlocke** [Financial-Times/o-fonts#13]
`oFontsGetFontFamilyWithFallbacks(BentonSans)` currently returns `BentonSans, Helvetica, Arial, sans-serif;`

I think it should just return `BentonSans, sans-serif;`

This automatically gives you Helvetica on OSX and Arial on Windows, which is what we want. The current fallback stack risks selecting Helvetica on Windows – this is bad, because quite a few Windows users do have *something* called "Helvetica" installed, and it's usually some shitty version with terrible hinting, spacing etc.

Also picking `sans-serif` guarantees you something clear and readable on all versions of Android and Linux desktops. It doesn't guarantee you consistency between platforms, but then again nothing does. Helvetica looks nothing like Benton anyway. This is a fallback situation so we might as well just ask for "the best generic sans-serif available".

For Clarion etc I would suggest `Clarion, Georgia, sans-serif`, because almost every system has a decent version of Georgia installed, so we might as well use that as the first fallback.

**Comment by kaelig** [comment]
Fixed in #29
