### ISSUE TITLE
Map the `light` font weight to `300`

### ISSUE THREAD

**Issue by notlee** [Financial-Times/o-fonts#132]
We curerntly map a "light" font weight to `200` but should map to `300` inline with the [OpenType specification](https://docs.microsoft.com/en-us/typography/opentype/spec/os2#usweightclass).
This may be important if we want to switch to variable fonts with equivelent weights maped to OpenType standards.

https://github.com/Financial-Times/o-fonts/blob/521d0f084fb72ec40a889e0f6d8719154385e24a/src/scss/_variables.scss#L116

I don't think this should be considered a breaking change as:
- Its not visually breaking if using `o-typography` or `oFontsWeight`, only if setting `font-weight: 200` directly.
- MetricWeb light is not used often (not on ft.com, not knowingly elsewhere)

**Comment by JakeChampion** [comment]
Nice find Lee!
I agree that this should likely not be a breaking because as you mentioned, the API we expose would not be changing.

**Comment by chee** [comment]
yes!
