### ISSUE TITLE
Remove Clarion (and leave Miller for now)

### ISSUE THREAD

**Issue by triblondon** [Financial-Times/o-fonts#20]
Replace all uses of Miller and Clarion with Georgia (which is a standard OS web safe font) and drop Miller and Clarion from o-fonts.

19/12/2014: Update by @kaelig: as stated by @pauloneillft https://github.com/Financial-Times/o-fonts/issues/20#issuecomment-67507964, we should remove Clarion but leave Miller for now)

**Comment by AlbertoElias** [comment]
I believe this is done
