### ISSUE TITLE
403 Forbidden when trying to load Metric

### ISSUE THREAD

**Issue by callumlocke** [Financial-Times/o-fonts#23]
I'm getting cross-origin errors when using my local dev server. I tried adding `local.ft.com` to my hosts file, and using that instead of localhost, but it still doesn't work. Am I doing something stupid?

![image](https://cloud.githubusercontent.com/assets/250617/4573091/778b4576-4f8e-11e4-972a-877ec6d42f9d.png)

**Comment by samgiles** [comment]
Closing this.  If this happens again we should revisit the bower module caching logic.  If the registry URLs are changed we'll see this issue again but I'd consider that to be an edge case.
