### ISSUE TITLE
Metric disappeared even from old versions

### ISSUE THREAD

**Issue by callumlocke** [Financial-Times/o-fonts#27]
Metric has just disappeared from this build service stylesheet:

http://build.origami.ft.com/bundles/css?modules=o-fonts@1.4.1

I was using `@1.4.1` (without `^`) because I need Metric, and it was there this morning, but it has just disappeared at some point in the last hour or two.

I can switch to `1.4.0`, but will it disappear from there too?

**Comment by kaelig** [comment]
Thanks for reporting that bug.

http://build.origami.ft.com/files/o-fonts-assets@0.2.2/metric-italic.ttf fails load.

![screenshot 2015-01-07 11 34 38](https://cloud.githubusercontent.com/assets/85783/5644962/6255969c-9661-11e4-9da1-652674ce8e1f.png)

@samgiles @AlbertoElias do you know what happened there?

**Comment by kaelig** [comment]
Closing as this apparently hasn't been an issue for some time.
