### ISSUE TITLE
Any reason why only 4 Metric weights are available?

### ISSUE THREAD

**Issue by callumlocke** [Financial-Times/o-fonts#30]
We want to use Metric semibold in IG projects, but I can't see it at http://registry.origami.ft.com/components/o-fonts

cc @sdbernard

**Comment by sdbernard** [comment]
Can I also add it would be good to get the light and thin variants in there also. We should have everything that is available in print for use online.

**Comment by kaelig** [comment]
v2.0.0 will support more weights. By default a limited set will be available but you'll be able to override the configuration to load other variants.

**Comment by AlbertoElias** [comment]
Fixed in #35

**Comment by AlbertoElias** [comment]
@callumlocke Can this be closed?

**Comment by sdbernard** [comment]
But we don't have the light, medium or semi bold variants

**Comment by AlbertoElias** [comment]
@sdbernard You do, all available variants are [https://github.com/Financial-Times/o-fonts/blob/master/src/scss/_variables.scss#L40](https://github.com/Financial-Times/o-fonts/blob/master/src/scss/_variables.scss#L40)

**Comment by sdbernard** [comment]
ok cool, it's just not clear in the registry documentation, Normal strong, normal emphasis only infers regular, bold and italic

**Comment by AlbertoElias** [comment]
We didn't want to show a demo per variant as that would make the demo list incredibly long. I will add a note on the readme that links to the list of all variants though. Thanks for the feedback!
