### ISSUE TITLE
Tabular numbers variant on Metric

### ISSUE THREAD

**Issue by kavanagh** [Financial-Times/o-fonts#40]
We'd like to be able to use `font-variant-numeric` and `font-variant: tabular-nums` for displaying numbers in tables and graphics. 

Metric already comes with these and are embedded into the Open type family. In fact all paper graphics already use these.

__What's different?__

* Most importantly, the glyphs/characters are monospaced.

![numbers____132___rgb_preview_](https://cloud.githubusercontent.com/assets/684559/6152487/7e62795c-b215-11e4-9058-ed8b3778ccbf.png)

* In Metric the number 1 is a different glyph.

![fwd__monospace__tabular_type__-_luke_kavanagh_ft_com_-_ft_mail](https://cloud.githubusercontent.com/assets/684559/6151769/dd4fdf14-b20f-11e4-9dae-582def6e9554.png)

__Why do this?__

Numbers in tables and charts tick labels line up vertically and so are easier to read.

Note: These should also probably be use on the big-number module.

Some background..
* [`font-variant`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant)
* [`font-variant-numeric`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-numeric)

**Comment by kaelig** [comment]
I'm in favour of having those in the base fonts only if it passes QA. In some versions of WebKit/Blink I've had issues (as in: text not displaying at all) when turning on any text-related features, maybe these are issues of the past but please have a thorough look.

**Comment by kavanagh** [comment]
We need to get a version of the woff/woff2 file with these in so we can test. Bit difficult to pass QA without the font file containing this.

Anyway, I thought these features were meant to be back compatible and not break things.

**Comment by kaelig** [comment]
Have a go at it, and if our users tell us there is a problem we can still revert back.

**Comment by kavanagh** [comment]
How do we do that. We need versions of the files with the correct stuff in. Do you know how to make those?

**Comment by kaelig** [comment]
At some point we'll have the necessary variants. For now it's not standardised.

**Comment by kavanagh** [comment]
We still need this.

Any idea when we'll have the better/remade version of MetricWeb available?

What can we do to get monospace digits in there? We really need these for charts.

**Comment by kavanagh** [comment]
Actually this currently works. Seems my test didn't take into account browser support ie. chrome needs the webkit prefix on `font-feature-settings` and doesn't support `font-variant-numeric` at the moment.Firefox is good and supports both without a prefix.

So you need this to make it work

```css
.tabular-nums {
    font-feature-settings: 'tnum' 1;
}
```

**Comment by kaelig** [comment]
Great to hear that it works, thanks for looking into it!

@danskinner: will the reduced charset of the Metric font include tabular numbers variants?

**Comment by kavanagh** [comment]
And, @danskinner any idea when that will be available to use?

**Comment by danskinner** [comment]
I don't think anyone's thought about monospaced characters before - @kavanagh is this something that's essential? And would that be just 0-9?

Nothing's been requested yet for MetricWeb - the sizing issue hasn't really been an issue in reality so hasn't seemed worth the time/expense to get refactored. We ought to request a reduced character set still though.

**Comment by kavanagh** [comment]
Yes, it's essential. You'll notice in the paper all charts and tables with numbers use these and it's familiar to those making charts and tables. It's also pretty simple to implement in CSS as I've shown above: you'd add those lines to the data table and big number CSS, and we'd also use it in [o-charts](https://github.com/ft-interactive/o-charts)

I'm not very familiar with what you have to do when making the woff2 font file but it's all characters for numbers (including decimal point and comma), and letter spacing data... you're basically including all the OpenType tabular numbers features into the font. 

In Font Squirrel you'd probably use "expert" mode and adjust the settings with something like the following...

![create_your_own__font-face_kits___font_squirrel](https://cloud.githubusercontent.com/assets/684559/9037679/9cb004e4-39e5-11e5-876b-7aa86f9af1b4.png)

Regarding the size issue, it is a problem when `@font-face` is not supported as the font sizes in the fallback sans-serif come out a lot bigger. With o-charts this causes layout issues as the height of a text label is critical to the layout of a chart.

**Comment by danskinner** [comment]
Thanks @kavanagh. Would you mind sending me a description of exactly what you'd require so I can pass that on and get it quoted?

Re font sizing, it's also a potential issue on slow connections when the fallacy font loads first for the same reason, but it's not something we've seen in practice with font cacheing. I see how it'd be an issue if font-face isn't supported, but that presumably only really apply to IE8 users. How serious is the display issue usually?

**Comment by kavanagh** [comment]
Regarding tabular numbers, we don't need to do anything unless we decide we want to change the files to _exclude_ certain glyphs. At the moment everything works just fine.

If we do decide to reduce the font file in some way then we just need to tell whoever is doing it to keep the 'tabular lining' aka 'tabular numbers' features of the OpenType set... and do this for all the weights we are using on the web. There are loads of OpenTypes features and I thought we'd have to go through each individually and decide whether to include or exclude.

For the font sizing thing, I don't know what should be done. Font squirrel has some voodoo called 'X-height matching' where you can adjust the size information so that the x-height of your font (i.e Metric) matches the x-height or a common system font, such as Arial. So I guess something along those lines?

See screenshot from Font Squirrel...

![create_your_own__font-face_kits___font_squirrel](https://cloud.githubusercontent.com/assets/684559/9040393/befae2ee-39f9-11e5-8f3f-613d8892301a.png)
