### ISSUE TITLE
Add TTFs back into o-fonts-assets?

### ISSUE THREAD

**Issue by callumlocke** [Financial-Times/o-fonts#43]
I realise these are no longer needed for browsers. But designers and developers still need to have these fonts installed for use in Illustrator etc. I've got various old TTFs knocking about, but I'm not sure if they might be outdated versions (e.g. with different base line height, different unicode ranges etc) compared to what we serve to browsers these days.

It seems like the private o-fonts-assets repo would be a good place to store reference TTF versions of our fonts, guaranteed to have complete parity with the corresponding WOFFs at the same commit.

**Comment by kaelig** [comment]
Agreed!

@danskinner @AlbertoElias what do you think? Can we sort this out in the next few weeks or should we wait for an updated Metric file?

**Comment by danskinner** [comment]
It makes sense in principal. Metric will (hopefully) change of course, but maybe we should add the latest versions we have for now anyway and replace when needed.

**Comment by callumlocke** [comment]
Yeah put the latest ones in now and replace with new ones when they're ready, that's what version control's for :)

**Comment by kaelig** [comment]
@callumlocke your mission if you accept it is to gather the files that work on PC/Mac and put them into the Stash repository.

**Comment by callumlocke** [comment]
It looks like the last point that the repo contained any TTFs was [this commit](http://git.svc.ft.com/projects/ORIG/repos/o-fonts-assets/commits/72511823dd4c478a52648ab1f18b5f46cb8515cd). So these are the latest files I can find.

[The following commit](http://git.svc.ft.com/projects/ORIG/repos/o-fonts-assets/commits/fac1837eaabbcf8d981f2671932e106975a35849) removed all the TTFs permanently. The problem is, this commit also updated several of the WOFFs to newer versions, and there may well be further commits after that that modified the WOFFs some more. So if we just restore the TTFs, then they will be out of sync with the latest WOFFs.

The question is, where did the current WOFFs in master come from? Who built them? From what?

**Comment by AlbertoElias** [comment]
The ttfs for the older fonts (Benton and Miller) are the same, those fonts haven't changed. For both Financiers and Metric, they were sent by the Foundry and probably @danskinner has them

**Comment by kaelig** [comment]
o-fonts-assets has moved to GitHub. Please take the conversation in this thread: https://github.com/Financial-Times/o-fonts-assets/issues/1
