### ISSUE TITLE
Sort Metric out

### ISSUE THREAD

**Issue by kavanagh** [Financial-Times/o-fonts#51]
I'm not sure if this is being sorted out or if the issues are properly understood. It seems that the problem isn't simply that the x-height is smaller than Helvetica/Arial/BentonSans. The issues are also to do with vertical alignment (and space below the glyphs) as well kerning.

I'm working on a project and just did a straight swap from BentonSans to Metric.

**Before**:

![the_everything_store_by_brad_stone](https://cloud.githubusercontent.com/assets/684559/9138191/35375a32-3d1a-11e5-9ab4-848104e15847.png)

**After**:

![the_everything_store_by_brad_stone](https://cloud.githubusercontent.com/assets/684559/9138208/4aab510c-3d1a-11e5-877b-d8a5c0427633.png)

* You'll notice the that the text is a lot smaller in the second picture. 

* The space below the descenders is huge: checkout the distance below the 'y' character. What's shown in the before image (with Benton) is normal – there shouldn't be much space below the glyphs. You can see this again in the red dot symbol: the 'W' in the second screenshot is too high up. Same with 'CATEGORY' to the right of the select box.

* Also if you do a bit of experimenting yourself you'll find that incrementing the size of text by only a couple of pixels increases the width of words much more in Metric. I put this down to something wrong with the kerning data in the font. This is a guess but I have some evidence: below you will see the black text from the browser rendering of MetricWeb overlaid with red Metric in illustrator. You'll notice I have aligned the beginning of each word and in all three cases the browser (black) text came out wider.

![untitled-1____300___rgb_preview_](https://cloud.githubusercontent.com/assets/684559/9138575/9aeb40ee-3d1c-11e5-9396-25608add81eb.png)

* I don't think the edges are as sharp. My guess is either the alignment of the glyphs in the file could be adjusted or it's do with the whole typeface being a bit smaller.

cc @danskinner @kaelig @AlbertoElias

**Comment by peter-mouland** [comment]
:+1: very interested in any conversations around this also...

**Comment by danskinner** [comment]
@kavanagh Is the live example above definitely using MetricWeb via Origami? The vertical alignment was an issue in the original .otf version of Metric we received and I asked the font designer to recut it to fix it - MetricWeb should behave properly.

The current issues, as I understand them, are that it's still very small and that the desktop and web versions are now so different. For the latter we should just convert the .woff into .otf and use that. The sizing issue is an annoyance but hasn't (yet) proved to be too much of an issue in practice.

Might be worth catching up this week - need to ensure we get this right.

**Comment by kavanagh** [comment]
@danskinner Yes, I'm using the latest o-fonts. But [I cannot see a commit on o-font-assets](http://git.svc.ft.com/projects/ORIG/repos/o-fonts-assets/commits) that corrects the baseline alignment on Metric

As I said above, it's not just that the text is small. The kerning is an issue too, and the baseline alignment is too high.

At the moment I can't vertically align stuff without CSS hacks eg messing with margin and padding to correct alignment.

The kerning issue makes it difficult to control the size of text, especially at smaller sizes. As you increase the size by only a few pixels the width of words increases disproportionately.

Perhaps we shouldn't rely on Klim to get this right.

**Comment by danskinner** [comment]
@kavanagh This is mildly perplexing - what you're seeing isn't something we've seen for a long time. Are you seeing the same issues on Next for example?

**Comment by kavanagh** [comment]
This turned out to be a little rabbit warren of issues cause by my :facepalm: typo ... I was using the System font. Shoot me now.

Metric is still irritatingly small though. And the medium weight has weird kerning... didn't know that.
