### ISSUE TITLE
Split fonts

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-fonts#57]
Would it be possible to split each of our fonts into 2 variants 
- core characters (latin + numeric + common punctuation... maybe the odd umlaut too)
- all the rest

Then o-typography's font stacks could be something like

```
font-family: MetricSansCore, MetricSansExtended, Sans-serif
```

Which would make most of the text in most articles load far quicker due to the much reduced font file needed for most characters

(Disclaimer - this might be totally mad and not actually work) @AlbertoElias @alicebartlett @keirog

**Comment by wheresrhys** [comment]
We could do some analysis of content and make the core character set 'characters used in 99% of articles'

**Comment by AlbertoElias** [comment]
Our intention and something we've talked about a lot is to just have just
one core font

-- 

------------------------------

*This email was sent by a company owned by Financial Times Group Limited 
("FT Group <http://aboutus.ft.com/corporate-information/#axzz3rajCSIAt>"), 
registered office at Number One Southwark Bridge, London SE1 9HL.  
Registered in England and Wales with company number 879531. This e-mail may 
contain confidential information. If you are not the intended recipient, 
please notify the sender immediately, delete all copies and do not 
distribute it further.  It could also contain personal views which are not 
necessarily those of the FT Group.  We may monitor outgoing or 
incoming emails as permitted by law.*

**Comment by onishiweb** [comment]
Where did Next get to on the fonts work they were doing? Is it something now that could be look at being brought back into Origami?

**Comment by keirog** [comment]
It's not really ready to go back in yet as it was only hackily implemented, for some annoying reasons that have since gone away. Tidy-up work is pending, hopefully coming next week for whoever's on Next bug duty. One of us will join the Origami meeting next week to discuss approaches.

**Comment by keirog** [comment]
Am definitely in favour of us exploring reduced-character fonts btw

**Comment by onishiweb** [comment]
:+1: Cool, thanks for the update. Will look forward to discussing this soon then.

**Comment by gvonkoss** [comment]
Closing this as it is no longer relevant, if there are any further developments on it, feel free to reopen.
