### ISSUE TITLE
Build service v2

### ISSUE THREAD

**Issue by callumlocke** [Financial-Times/o-fonts#59]
Should the `$o-fonts-path` be updated to load o-fonts-assets via v2 of the build service?

i.e. this line
https://github.com/Financial-Times/o-fonts/blob/47429689765b8915c8e8e1b9d97756e216f9e2d8/src/scss/_variables.scss#L9

**Comment by AlbertoElias** [comment]
Oh! Thanks for spotting that!

**Comment by AlbertoElias** [comment]
Fixed in 3580c11
