### ISSUE TITLE
Less jarring font fallback stacks

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-fonts#64]
Inspired by this slide onwards http://webtypography.net/talks/rdo13/, it'd be a less noticeable FOUT if we try to find fallback fonts which are more similar to metric and financier (which are both very different to arial/helvetica and georgia)

e.g. TamilSangamMN is far more similar to Metric than arial/helvetica

**Comment by onishiweb** [comment]
This would be a good resource for ensuring we have good OS coverage for the fallbacks as well: http://fontfamily.io/Tamil_Sangam_MN

**Comment by onishiweb** [comment]
Closing in favour of https://github.com/Financial-Times/o-typography/issues/97
