### ISSUE TITLE
When calling with the build service, font assets are delivered from the old domain

### ISSUE THREAD

**Issue by antoligy** [Financial-Times/o-fonts#66]
Hey,

When calling the o-fonts from the build service, the CSS that is returned points to build.origami.ft.com - 
e.g. https://origami-build.ft.com/v2/bundles/css?modules=o-fonts@%5E2 returns links like `//build.origami.ft.com/v2/files/o-fonts-assets@1.3.0/BentonSans-Light.woff?#iefix`

Meanwhile `$o-fonts-path` in this repo defaults to `//origami-build.ft.com/v2/files/o-fonts-assets@1.3.0/`

**Comment by rowanmanning** [comment]
Ah it looks like the work was done but never tagged and released. I'll do that now, thanks for pointing out!

**Comment by rowanmanning** [comment]
Hi @antoligy, I've released o-fonts `2.1.3`. Currently your URL still loads `2.1.2` but that should change once the cache clears. Just to verify that this is now working: https://origami-build.ft.com/v2/bundles/css?modules=o-fonts@%5E2.0.0

**Comment by rowanmanning** [comment]
https://origami-build.ft.com/v2/bundles/css?modules=o-fonts@%5E2 now has the correct font paths. Gonna close this, let me know if you have any issues

**Comment by antoligy** [comment]
Nice one, thanks!
