### ISSUE TITLE
Allow `font-display` property to be specified

### ISSUE THREAD

**Issue by Limess** [Financial-Times/o-fonts#87]
It'd be nice to be able to specify `font-display` for each/every font being output.

References:

* https://developers.google.com/web/updates/2016/02/font-display
* https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display

**Comment by rowanmanning** [comment]
This will be included in the next major: #94 (there's already a proposal here also https://github.com/Financial-Times/o-typography/issues/195)

**Comment by notlee** [comment]
🙃

**Comment by notlee** [comment]
Done, to be released in the next major release as part of the major cascade, see https://github.com/Financial-Times/o-fonts/pull/100
