### ISSUE TITLE
Bold and italics together not supported with font-weight: 600 and MetricWeb

### ISSUE THREAD

**Issue by petrklus** [Financial-Times/o-fonts#95]
A bug report for MetricWeb - missing webfont?

## What

When using `font-weight: 600` and **strong** and _em_  together, the resulting text boldness is not accurate (matches the boldness of the bold above).

## Details

Please see below a screenshot from the Origami MetricWeb demo - all elements on the last line use `font-weight: 600`

![image](https://user-images.githubusercontent.com/1115667/64879453-4c786180-d656-11e9-919a-a068217f90f4.png)

**Comment by notlee** [comment]
Hey @petrklus, for performance we try to limit the number of custom fonts we load and provide a [limited set](https://github.com/Financial-Times/o-fonts#fonts-available). The italic font for MetricWeb is available in light (200), regular (400), and bold (700).

**Comment by notlee** [comment]
I'm going to close this for now @petrklus, but let me know if you would like to discuss the fonts we have available

**Comment by petrklus** [comment]
Hi @notlee , thank you for coming back to me - what would be the recommended approach if we needed to use the italics at weight 600?

**Comment by notlee** [comment]
Hey @petrklus, we'd like to avoid adding a new font if it might introduce design inconsistency or increase page weight of an existing product, but there are cases where adding a new font to o-fonts is appropriate. What product(s) would like to use the new font in and which designer would like to introduce it?

**Comment by petrklus** [comment]
Hi @notlee , thank you for following up - I have asked our design team to send an email with further details on this, which you will be receiving shortly.

**Comment by notlee** [comment]
Hey @petrklus, further to our emails I'm going to close this issue again. Feel free to email or Slack the team if you'd like to pick it back up

**For the reference of future readers:**

The font was needed because a WYSIWYG editor would allow content creators to use this combination. Potential effected sites include:

```
Subscriptions: https://subs.ft.com
Enterprise: https://enterprise.ft.com (N.B. We are in the process of redeveloping - https://beta.enterprise.ft.com/en-gb/services/group-subscriptions/)
About Us: https://aboutus.ft.com
Help Centre: https://ft1-235-helpftcom-stage.eu.aldryn.io/?sharing_token=c8dea636997c1db0cd219a62f7c915ad310ca35f262ce1939d15b0ece09fc269 (N.B. We are in the process of redeveloping)
Co-branded content hubs: e.g. https://meaningfulpursuits.ft.com / https://transact.ft.com / https://tech40.ft.com
scoutAsia: https://www.scout.asia
```

The Origami teams thoughts on this were:

>Our concern is, if we generate and document a new font, it will make its way onto ft.com and the app without design oversight or a review on the impact to page load times. For cases where a combination of styles can't be controlled due to a WYSIWYG, we'd suggest: opting for a weight of 700 for bold and bold with italics; or informing the user with a note in a WYSIWYG and using CSS to remove the italic style.
